### ISSUE TITLE
Getting null values when attaching multiple tags to uploaded files

### ISSUE THREAD

**Issue by marcopostmovares** [microsoft/PubSec-Info-Assistant#471]
When we attach multiple tags to a document that we upload in the Information Assistant Accelerator, this seems to go O.K. in the web interface in the upload phase (i.e. we're not getting any errors over there). However, when we then inspect the state of the uploaded data via the Azure Portal, those tags seem not to have been properly attached to the documents. The tags are also not associated with the file in Cosmos DB. Moreover, in Azure Blob Storage, there is the key-value pair "tags: null" in the "upload" container and no tags at all in the "content" container. The result of this is that we are not capable of adding multiple tags to a document, as all tags associated with this uploaded document also are not retrievable in the "Configure answer generation" section of the Chat.
![1 IAA upload tags via GUI](https://github.com/microsoft/PubSec-Info-Assistant/assets/87522903/ed2e9ed0-af22-4fe4-87fa-c06c8e4d2e2d)
![2 IAA tags in blob container upload](https://github.com/microsoft/PubSec-Info-Assistant/assets/87522903/f418d9ca-0d4e-4d10-8f7b-dd533a8137e4)
![3 IAA tags in blob container content](https://github.com/microsoft/PubSec-Info-Assistant/assets/87522903/2a029bda-e94c-4bd1-9d0b-bf8250ecbaab)
![4 IAA tags in cosmos db](https://github.com/microsoft/PubSec-Info-Assistant/assets/87522903/b70db547-2f3c-470f-b80a-e7459b6e070e)

**Comment by ryonsteele** [comment]
Hi marcopostmovares

I am unable to replicate this issue, but I have a suspicion on what could be causing it for you if I could get some more info from you.


Firstly, the tags would not show up in the Storage Account "content" container, only the "upload" container.
That metadata is then pulled by the backend enrichment app during file processing and stores them in CosmosDB tags table.
The fact they are showing as null in the upload container metadata, it makes sense they would then not show up in cosmos since that is where it sources from.

I tried with v1.0 multiple tags and could not reproduce.
I then added your specific examples in case it was something special with that alpha-numeric combination but still no replication.

CosmosDB record of one of the tested documents with multiple tags
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/88948334-1e07-45f8-a121-2f16274c1195)


Its upload container blob metadata:
![image](https://github.com/microsoft/PubSec-Info-Assistant/assets/17028127/125aed2b-5136-4ea8-b5e3-7825ebc52c8b)


If you could provide to us 
1) what release or branch you are working off of here?
2) any relevant modifications around the target areas?

Now my suspicion. Since the first point of failure in your example would be the Storage Account SDK in the front end code. I suspect a possible browser compatibility issue with the browser being used. if you could also provide.

3) Browser flavor and version/build number?

**Comment by marcopostmovares** [comment]
Hi ryonsteele,

Thank you for your reply. Please find below the answers to the questions that you have asked:

1. We have deployed a recent version of the Information Assistant Accelerator. The Git commit of the source code from this repo is: **27df39089a0a203c41ae153dc2539315559d0eeb**
2. No, we did not make any custom modifications to either the Python source code of the Azure Functions or of the target areas.
3. We interacted with the Web App of the Information Assistant Accelerator via the Microsoft Edge browser. The particular version we have used is: `Version 120.0.2210.144 (Official build) (64-bit)`

**Comment by marcopostmovares** [comment]
P.S. We have tried it again using a different browser: Mozilla Firefox, build version `121.0.1 (64-bits)`, but the problem occurs over there as well.

**Comment by ryonsteele** [comment]
Hey marcopostmovares

That all seems fine and should work. Only thing I can think to suggest is attaching a debugger and/or wrapping the target code in a try-catch and monitoring the browser dev tools.

Neither others or I can seem to replicate. Wondering if it's something with the file being used itself or some hidden unicode character failing to encode.

The target file would be app/frontend/src/components/filepicker.tsx

In there, is the logic to set those tags as metadata on the blob using the SDK
Try wrapping that like so:

try {
  await blobClient.uploadData(file, options);
} catch (error) {
  console.error("Error during upload:", error);
}

We'd be happy to patch if we can narrow down the cause or able to replicate. Doing this could shed light on what's happening.

**Comment by marcopostmovares** [comment]
Hi ryonsteele,

We did some further investigation on this issue and it turns out it was an error from our side. The UI is very sensitive about the order in which you fill in the fields in the "Manage Content" section of the Web App. As long as you fill in the fields in the right order, the tags are attached O.K., but if you deviate from this order or change your mind about the values you fill in in a previous fields later on, then the tags is set to "null". This is precisely as documented, so in that sense not strictly a bug, but it would perhaps be a little bit more user-friendly if the UI was a little bit less sensitive about the order in which you fill in the fields.

**Comment by ryonsteele** [comment]
Understood, thank you for the feedback!
